repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 72c60aca479dce0593d6d28e2f006dbc484d8684 # v1.8.35
    hooks:
      - id: terraform_fmt
      #- id: terraform_docs
      - id: terraform_tfsec
      - id: terraform_validate
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color
